### PR TITLE
Fix calendar scroll

### LINKED ISSUE #38: Calendar scrolling lag
Months scrolling lags heavily after last update.
Moreover seems like the whole wingpanel freezes. I'm using `System Load Indicator` and it's stops for a while on calendar scroll.

I've got a PC that powerful enough:
- Quad-Core Intel® Core™ i5-3570K CPU @ 3.40GHz
- 12.0 GB memory

And it wasn't like this before update.
So it seems like a bug.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/46846207-calendar-scrolling-lag?utm_campaign=plugin&utm_content=tracker%2F57456330&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57456330&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #38 

Import smooth-scrolling logic from wingpanel-indicator-sound to replace Util.on_scroll_event (). This gives a more even and controllable scrolling using mouse and touch.  Also respects natural scrolling settings.

### CODE REVIEW

**Comment by jeremypw** [comment]
@danrabbit . I fixed the scroll direction.  However I find this much easier to control than master because the calendar *always* scrolls when you swipe and with the same delta per month.  If you swipe slowly then the calendar scrolls slowly, whereas if you swipe faster the calendar scrolls faster.  In master , if you swipe too slowly then the calendar never scrolls and the delta per month depends on the speed of swipe.

I can increase the delta per month (lines 282 , 284) from 2.0 to 3.0 or higher  if you think the controllability is insufficient.

**Comment by jeremypw** [comment]
I have pushed a new version which puts the logic into CalendarView.vala and reduces scroll sensitivity to swiping.   Also, scroll events are ignored during transitioning.  Mouse scrolling events are adjusted so that one month per click of scroll wheel is maintained.

**Comment by jeremypw** [comment]
I have had to add a "hack" to deal with touch devices that are incorrectly reported as Gdk.InputSource.MOUSE (causing too fast scrolling).

**Comment by danrabbit** [comment]
Requesting a review from @tintou here since I believe he wrote the scroll handling for the applications menu

**Comment by jeremypw** [comment]
OK, good idea.  The code here was originally intended for controlling a scale widget.  There may well be a better solution for switching a stack by scrolling.

**Comment by tintou** [comment]
I'd prefer to wait until we get proper gesture support in the Gtk stack with GtkGesture (something like https://valadoc.org/gtk+-3.0/Gtk.GestureSwipe.html )

**Comment by jeremypw** [comment]
OK, the current behaviour is usable 'til then.

**Pull request closed without merging**
