### PR TITLE
Fix get_keys warning

### PR DESCRIPTION
**Pull request by donadigo**
Fixes `hash_table_get_keys` warnings. It is strongly not recommended to initialize class fields in a thread and using them without knowing if they did really initialize at the usage time. This class would do that almost every time since it calls `load_all_sources` not in the constructor but after creating the class object which is doing initializing in a thread. This branch fixes it.

### CODE REVIEW

**Comment by parnold-x** [comment]
mhh one of the sync method needs some time not sure which one. Did you check for a delay?

**Comment by donadigo** [comment]
@parnold-x yes, I did check what method needs time, it looks like it was `Process.spawn_command_line_sync`. I've moved only initialization of fields, not this one.

**Comment by parnold-x** [comment]
@donadigo nope it was one of the eds functions.  You did move everything eds related from the thread. Do you have data in eds? Or they speed up their initialization.

**Comment by donadigo** [comment]
@parnold-x unfortunately I don't think I have any data in EDS and the only thing I see that could take some time to initialize is `registry = new E.SourceRegistry.sync (null);` but since `registry` is a public property and is used elsewhere in the class, making it threaded doesn't make sense to me, there is also a `foreach (var source in registry.list_sources (E.SOURCE_EXTENSION_CALENDAR))` which adds some sources, this could be put into a thread if needed.

**Comment by parnold-x** [comment]
the purpose to make it threaded was that it took 2-3s. That was the delay on startup, so it was needed...

**Comment by donadigo** [comment]
@parnold-x should we revert it then?

**Comment by parnold-x** [comment]
Your call. Wanted to just clearify the original purpose of the threaded init.
To fix the warning is it enough to just do the hashtable inits in the construct?

**Comment by donadigo** [comment]
Yes, it is enough to do inits of HashTable's, but as I said, putting other fields into treaded initialization could create some problems in the future. We should make sure that these get initted before we use these. I can propose a merge for reverting this and initting only the HashTable's if you want.

**Comment by parnold-x** [comment]
Would be better because a 3s lag at start is significant.

**Comment by parnold-x** [comment]
looks good. Can't approve.

**Pull request merged**
