### PR TITLE
Replaces undef

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #9
Blocked by string freeze

### CODE REVIEW

**Comment by danrabbit** [comment]
Looks like this needs a look over by @elementary/ux

**Comment by cassidyjames** [comment]
Does this mean, "Can't get the local time." will show as the time when we can't get the time? I honestly think just not showing the clock may be better…

**Comment by cassidyjames** [comment]
Whoops, wrong button.

**Comment by peteruithoven** [comment]
Yeah, if the following results in null, 
```
var local_time = new GLib.DateTime.now_local ();
```
which is probably an edge case. you get: 
screenshot from 2018-11-03 10 09 30
screenshot from 2018-11-03 10 09 33

One benefit of this is that it's probably clearer for the user. 

But indeed we could also just hide the indicator. That's what we usually do in indicators and plugs when hardware isn't found.

**Comment by cassidyjames** [comment]
Revisiting this: can we fallback to _some_ sort of time instead of taking away the clock completely?

**Comment by leonardo-lemos** [comment]
Is it possible to fallback to the hardware time?

**Comment by jeremypw** [comment]
How likely is it that this DateTime function fails? The issue seems more theoretical than an actual bug.  I suppose it might fail if (a) the system time is unavailable or invalid or (b) the timezone is unavailable or invalid. Neither seem likely.  Maybe we could fall back to trying to show a DateTime constructed from get_monotonic_time () and the local timezone (or if the timezone is invalid use utc)?

**Comment by danrabbit** [comment]
I'm gonna close this since it's had conflicts for over a year

**Pull request closed without merging**
