### PR TITLE
Indicator: open Calendar on middle-click

### LINKED ISSUE #286: Provide middle-click action to open current day in calendar
### Problem

Opening the Calendar at the current day takes at least two steps, which are not entirely obvious
 - open the indicator
 - double-click on current day

### Proposal

Provide a middle-click action for the indicator that opens the current day in the Calendar app.

### Prior Art (Optional)

Several  other wingpanel indicators already  provide a middle-click action for a commonly used function, together with a tooltip.

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #286

### CODE REVIEW

**Comment by marbetschar** [comment]
Not tested yet, but I _think_ the tooltip is missing which is displayed on other elements in Wingpanel for the middle click, such as:

Screenshot from 2021-12-04 11-08-01@2x

**Comment by marbetschar** [comment]
Possible text for the tooltip (depending on state):

**1 event and 3 tasks planned for today**
_Middle-click to open Calendar_

Other states:

- If there are events but no tasks:
  - 2 events planned for today
- if there are tasks but no events:
  - 1 task planned for today
- if there are no events and no tasks:
  - Nothing planned for today

**Comment by danrabbit** [comment]
@marbetschar I added a tooltip for the middle click action, but I think adding a summary is a bit outside the scope of this branch

**Comment by marbetschar** [comment]
LGTM - feel free to merge, because I lost the ability to merge because I merged from master ... again :)

**Pull request merged**
