### PR TITLE
Rewrite styles for Greenfield

### PR DESCRIPTION
**Pull request by danrabbit**
Supersedes #219 
Supersedes #188 

Requires greenfield

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit is this intended to address dark style, or just light for now?

**Comment by cassidyjames** [comment]
Ah, I see this is just for the calendar grid and not for events themselves which are broken in dark style in master.

**Review by cassidyjames — CHANGES_REQUESTED** [review]
Nice improvement. Make sure to update release CI so we can't accidentally release to Hera.

**Comment by danrabbit** [comment]
@cassidyjames release branch should be odin now

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
