### PR TITLE
Display tasks in Wingpanel

### LINKED ISSUE #211: Add support for tasks
Since we are building an [elementary Tasks app](https://github.com/elementary/tasks/), we should also consider showing tasks along with events in wingpanel-indicator-datetime.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91335242-add-support-for-tasks?utm_campaign=plugin&utm_content=tracker%2F57456330&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57456330&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by marbetschar**
This PR fixes #211.

Screenshot from 2021-03-01 18-57-16

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
This looks like there's a lot of good cleanup with naming things more accurately etc, but I can't verify that it actually shows due tasks:

Screenshot from 2021-06-15 11 25 36

It looks like there is a dot in the calendar view with the correct color, but no row for the task

**Comment by marbetschar** [comment]
@danrabbit fixed the display issues. Can you please re-review?

**Comment by marbetschar** [comment]
@danrabbit any chance we can get this merged before release, or is the window already closed?

**Comment by danrabbit** [comment]
Tbh I haven't had a chance to test this at all! I'm sorry. But I think we could prioritize it for shortly after release as an update :) I'll add it to the post-release project board so we don't forget

**Comment by danrabbit** [comment]
@marbetschar apologies for taking so long to follow up on this! can you resolve conflicts here?

**Comment by marbetschar** [comment]
@danrabbit nevermind! I resolved the conflicts. However, there now seems to be an issue with timezones (the displayed time for the task is off on my end). Do you also see any such thing on your end?

I'm not entirely sure were to tackle this - maybe its even an issue with how Tasks stores the time initially. @mcclurgm any chance you got some time to have a look what's off with TImeZone calculations here?

**Comment by mcclurgm** [comment]
I'll see if I can spare some time this evening. 

I've been wondering about Tasks timezones in general, I feel like it might be useful to store them as floating times. That's an issue for design though, I'll plan to open an issue to discuss.

**Comment by mcclurgm** [comment]
I think the issue here is that we're not converting the time zone in the Tasks code. I have a task that shows up as 13:05 in Tasks, but 6:05 in wingpanel. I checked in Evolution, and the task is actually at 13:05 UTC, which is 6:05 local. So the issue is the way we're handling timezones in Tasks code, Wingpanel is doing things properly.

**Comment by marbetschar** [comment]
@danrabbit since you added this to the release draft: Does https://github.com/elementary/tasks/issues/312 prevent us from releasing this?

**Review by danrabbit — APPROVED** [review]
Let's get this in and we can test further in early access :)

**Pull request merged**
